# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  jarName: 'asset-management-0.0.1-SNAPSHOT.jar'
  artifactName: 'drop'
  azureSubscription: 'MyAzureConnection'
  appName: 'asset-management'

steps:
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package -DskipTests'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: CopyFiles@2
    inputs:
      contents: '**/target/*.jar'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appName: '$(appName)'
      package: '$(Build.ArtifactStagingDirectory)/target/$(jarName)'
      runtimeStack: 'JAVA|21-java21'
