version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: asset_management_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - asset_management_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: maven:3.9.8-eclipse-temurin-21
    container_name: asset_management_app
    volumes:
      - ./src:/app/src # Mount the current directory to /app in the container
      - ./pom.xml:/app/pom.xml # Mount the pom.xml file
      - ./.env:/app/.env # Mount the .env file
      - ./mvnw:/app/mvnw # Mount the Maven wrapper script
      - ./mvnw.cmd:/app/mvnw.cmd # Mount the Maven wrapper script for Windows
      - ./logs:/app/logs # Mount the logs directory
      - maven_cache:/root/.m2 # Cache Maven dependencies
    working_dir: /app
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - asset_management_network
    depends_on:
        postgres:
            condition: service_healthy
    command: ["mvn", "spring-boot:run"]

volumes:
  postgres_data:
  maven_cache:

networks:
    asset_management_network:
        driver: bridge
